server:
  #指定启动端口号
  port: 8080
  #配置次路径后，所有的资源访问路径都会加上前缀
  servlet:
    context-path: /yinxiang

#Spring Boot Actuator
management:
  server:
    port: 8088

logging:
  config: ./src/main/resources/logconfig/logback-spring-dev.xml
  # 日志文件,绝对路径或相对路径
  # file: ./log/yinxiang-dev.log
  # 日志级别
  # level:
  #        com.yiinxiang.helloworld.GreetingController: debug

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
      default-property-inclusion: non_null
  datasource:
      driver-class-name:
      username: chen
      password: hsbc
      url: jdbc:mysql://193.112.35.196:3306/ordersys?characterEncoding=utf-8&useSSL=false

# JWT 认证配置
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800 #token七天不过期
  tokenHead: "Bearer "
  exceptUrl: "/auth/**"
